# Generated by Django 4.1 on 2022-08-04 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=300, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('postal_code', models.PositiveSmallIntegerField()),
                ('town', models.CharField(max_length=30)),
                ('phone_numer_1', models.PositiveSmallIntegerField()),
                ('phone_number_2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('TIN', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
                ('email', models.EmailField(max_length=260, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260, unique=True)),
                ('unit', models.CharField(choices=[('szt', 'szt'), ('m', 'm'), ('km', 'km'), ('op', 'op'), ('opz', 'opz')], default='szt', max_length=3)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('category', models.CharField(choices=[('kable', 'kable'), ('uchwyty', 'uchwyty'), ('budowlane', 'budowlane'), ('narzedzia', 'narzędzia')], default='budowlane', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260, unique=True)),
                ('client', models.CharField(default='', max_length=260)),
                ('start_time', models.DateField()),
                ('scheduled_end_time', models.DateField()),
                ('end_time', models.DateField()),
                ('description', models.CharField(max_length=260)),
                ('street', models.CharField(max_length=260)),
                ('house_number', models.PositiveSmallIntegerField()),
                ('postal_code', models.PositiveSmallIntegerField()),
                ('town', models.CharField(max_length=260)),
                ('budget', models.FloatField(blank=True, default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=260, unique=True)),
                ('net_price', models.FloatField(null=True)),
                ('TAX', models.FloatField(null=True)),
                ('gross_price', models.FloatField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERPapp.client')),
            ],
        ),
    ]
