# Generated by Django 4.1 on 2022-08-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERPapp', '0003_alter_project_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='postal_code_1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='postal_code_2',
        ),
        migrations.AddField(
            model_name='project',
            name='postal_code',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(default='', max_length=260),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(default='', max_length=260),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_time',
            field=models.DateField(null=True),
        ),
    ]
