# Generated by Django 4.1 on 2022-08-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERPapp', '0005_alter_project_client_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=260, null=True, unique=True),
        ),
    ]
