# Generated by Django 4.1 on 2022-08-11 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERPapp', '0008_alter_project_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 11)),
        ),
    ]
