# Generated by Django 4.1 on 2022-08-11 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ERPapp', '0010_alter_invoice_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='date',
            new_name='sales_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payday_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Wires', 'wires'), ('Cable Holders', 'cable_holders'), ('Building Materials', 'building_materials'), ('tools', 'tools')], default='Building Materials', max_length=100),
        ),
    ]
