# Generated by Django 4.1 on 2022-08-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERPapp', '0013_payment_check_alter_invoice_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'paid'), ('not paid', 'Not Paid')], default='not paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Wires', 'Wires'), ('Cable Holders', 'Cable Holders'), ('Building Materials', 'Building Materials'), ('tools', 'Tools')], default='Building Materials', max_length=100),
        ),
    ]
